//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    StudyMaterials: [
      {
        title: 'title 1',
        description: 'description 1',
        uploadDate: '2023-06-30T23:38:51.334Z',
        fileLink: 'fileLink 1',
        id: 43,
      },
      {
        title: 'title 2',
        description: 'description 2',
        uploadDate: '2024-06-29T01:00:30.471Z',
        fileLink: 'fileLink 2',
        id: 56,
      },
      {
        title: 'title 3',
        description: 'description 3',
        uploadDate: '2025-03-04T04:03:10.070Z',
        fileLink: 'fileLink 3',
        id: 36,
      },
      {
        title: 'title 4',
        description: 'description 4',
        uploadDate: '2024-12-10T07:42:32.451Z',
        fileLink: 'fileLink 4',
        id: 56,
      },
      {
        title: 'title 5',
        description: 'description 5',
        uploadDate: '2024-09-26T04:57:49.944Z',
        fileLink: 'fileLink 5',
        id: 3,
      },
    ],
  },
};
export default data;
