//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    StudyMaterials: {
      name: 'Study Materials',
      fields: {
        title: 'Title',
        description: 'Description',
        uploadDate: 'Upload Date',
        fileLink: 'File Link',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    StudyMaterials: {
      name: 'Study Materials (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        uploadDate: 'Upload Date (fr)',
        fileLink: 'File Link (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
